### ISSUE TITLE
Text dài hoặc chứa kí tự đặc biệt thì app dừng hoạt động

### ISSUE THREAD

**Issue by dominhduc** [phatjkk/SpeakIt_Vietnamese_TTS#1]
**_Issue:_** Text dài hoặc chứa kí tự đặc biệt thì app dừng hoạt động và thoát.

**_Reproduce:_**

1/ Mở app và paste đoạn text này từ CafeF:

> Đáng chú ý, đóng góp chính vào nhịp tăng vừa qua tập trung chủ yếu ở 4 cổ phiếu VIC, NVL, HPG và VHM với 40 điểm, trong đó VIC chiếm hơn ½ (22,6 điểm). Tuần vừa qua cũng là tuần tăng thứ 3 liên tiếp của chỉ số VN-Index, kể từ đầu năm cho tới nay, chỉ số này đã tăng 12,2%, cao hơn so với 2 chỉ số chính của thị trường chứng khoán Mỹ (S&P 500: + 11%, Dow Jones: + 11,2%) và chứng khoán khu vực châu âu (STOXX Europe 600: + 10,2%).

2/ Chọn giọng **Nam miền Bắc**

3/ Ấn **Đọc** và app tự động thoát

**Comment by phatjkk** [comment]
Cảm ơn bạn đã báo cáo, mình đã sửa lại lỗi chứa kí tự đặc biệt không đọc ở phiên bản 2.0.7.
Nếu có lỗi gì hãy góp ý mình nhé.
