### ISSUE TITLE
Thoát phần mềm dù có nhập bao nhiêu ký tự

### ISSUE THREAD

**Issue by dienquadi** [phatjkk/SpeakIt_Vietnamese_TTS#18]
Mình nghĩ do server zalo đã giới hạn lại free chỉ còn 500 char, và giới hạn về API nên phần mềm này giờ có lẽ không còn sử dụng được nữa rồi.

**Comment by paulscholes0258** [comment]
mình cũng bị vậy. app bị tắt liên tục ko thể sử dụng.

**Comment by dienquadi** [comment]
app báo lỗi là {"error_message":"You have exceeded your free quota for this demo","error_code":-429}
quota của tác giả bị hết hạn rồi

**Comment by hoaihung** [comment]
Mình fix tạm trong lúc chờ tác giả cập nhật bản sửa nhé.
1. Bạn vào folder zalo_tts và edit file zalo_tts.py
2. Tìm đến dòng url="https://zalo.ai..." (dòng số 7) và đổi url lại thành "https://api.zalo.ai/v1/tts/synthesize".
3. Save file và tiến hành thử lại (có thể xóa nội dung trong file output.txt để kiểm tra lỗi trả về rõ ràng hơn.
